// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.macOS: return macos;
      case TargetPlatform.windows: return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('DefaultFirebaseOptions have not been configured for linux.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKbjTmXkuLx95-KqurjyV7yo5x2IyTMdo',
    appId: '1:217167684754:web:2ba0e5a7ac8fa32bafb24b',
    messagingSenderId: '217167684754',
    projectId: 'st-step-staff',
    authDomain: 'st-step-staff.firebaseapp.com',
    storageBucket: 'st-step-staff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6vVt8Rwzy26GoqsVLDvjz3sllBdoAhlE',
    appId: '1:217167684754:android:4587c6d2cb67804bafb24b',
    messagingSenderId: '217167684754',
    projectId: 'st-step-staff',
    storageBucket: 'st-step-staff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9B6bxRqCrRPeo_6L9kDc8mh-dbEwtNrk',
    appId: '1:217167684754:ios:1abffd7ad2752ba1afb24b',
    messagingSenderId: '217167684754',
    projectId: 'st-step-staff',
    storageBucket: 'st-step-staff.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKbjTmXkuLx95-KqurjyV7yo5x2IyTMdo',
    appId: '1:217167684754:web:8fb23fcc5a955990afb24b',
    messagingSenderId: '217167684754',
    projectId: 'st-step-staff',
    authDomain: 'st-step-staff.firebaseapp.com',
    storageBucket: 'st-step-staff.firebasestorage.app',
  );
}
